# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      sudo chmod -R 755 .gitpod/scripts/
      mkdir -p .gitpod/logs
      source .gitpod/scripts/before.sh > .gitpod/logs/before.log
    init: | # runs during prebuild
      source .gitpod/scripts/init.sh > .gitpod/logs/init.log
    command: | # runs everytime when start
      source .gitpod/scripts/command.sh > .gitpod/logs/command.log
      # extra commands
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
